### PR TITLE
Make deconflicting properly recursive

### PR DESCRIPTION
**Pull request by dwincort**
## Description
In PR https://github.com/haskell-works/avro/pull/94, `deconflict` was updated to do some name resolution.  As the PR describes:

> The problem is that `deconflict` doesn't expand `TypedName` when traversing schemas. It only checks if the name matches, and if it does then it assumes that the value doesn't need to be deconflicted.

However, that PR does not go quite far enough.  The solution in that PR is to call `expandNamedTypes` (a function introduced in the PR) on the schemas before deconflicting.  This expands any found names, but it does not expand names that may come from other expanded names; in other words, it does not work on recursive data types.  See the new test cases derived from the modules  `Avro.Deconflict.D.Writer` and `Avro.Deconflict.D.Reader` for an example of this.

## Changes
In this PR, I have updated `deconflict` to carry around name-resolution environments (created by the `buildTypeEnvironment` function in `Data.Avro.Schema`), which it can use to dynamically look up names when they are found.  This additionally means that initial passes of `expandNamedTypes` are no longer necessary.

In PR https://github.com/haskell-works/avro/pull/94, there was a warning that expanding names increased the runtime of `deconflict`.  Fortunately, according to the benchmark suite, dynamic name resolution doesn't seem to make `deconflict` any slower.  However, it does make `deconflictNoResolve` about 15% slower.  Of course, this could probably be solved with a lot of code duplication (use entirely different functions for `deconflict` and `deconflictNoResolve`), but this seems ugly.  Perhaps a reviewer can see a way to make my code faster?

That said, it strikes me that `deconflictNoResolve` is, well, wrong, and I can't see any place where it should safely be used.  In PR https://github.com/haskell-works/avro/pull/94, it was argued that it could still be used when decoding containers, but as my test cases show, this isn't true in a general case.  It seems to me that any sort of performance hit is simply the price that must be paid for supporting recursive types (although it would be great if I were wrong about this).

### Final Notes
Thanks for considering this code, and since I didn't see any PR guidelines, please let me know if there's anything I can do to make it more acceptable.

### CODE REVIEW

**Comment by dwincort** [comment]
I don't mean to be pushy, but is there any timeframe on this?  Anything I can do?

**Comment by AlexeyRaga** [comment]
@dwincort I am TERRIBLY SORRY, my fault I somehow completely missed this PR and just noticed it now.
Reviewing right now.

**Comment by AlexeyRaga** [comment]
@dwincort 

Thanks for pointing out to the recursive case! Your code seems to handle it well, thank you!

I need to play with it a bit because taking 15% performance hit is quite significant for us as we process lots of large containers with very deep and complicated schemas. I suspect that because of these large schemas the performance hit for us could be more significant than 15%.

There ought to be a way of de-conflicting schemas once and then re-using the result for all these hundreds records in a container. By definition all the values within the container share the same schema so it should be possible to avoid doing the same work over and over again.

I will perhaps merge the PR (because it looks genuinely good), but will not make a new release until I have a solution (or until I give up).

BTW, I was thinking about it some (long) time ago, could we re-think deconflicting?
The problem is that it takes 3 values: reader schema, writer schema and a raw avro value. So for each avro value we perform deconflicting over and over again.

But what if we somehow make deconflicting only on the schema level?  We could deconflict _schemas_, get the _schema_ back and then simply use it for decoding values.
This will, most likely, require some changes in `Schema` data type. At least to indicate what fields are to be ignored by the reader. Perhaps some more information about how to resolve defaults.

But if we can pull this off, if we could have _one_ schema the we could use for decoding, then it would perhaps open doors to implement "direct" decoding (where we could go directly from `ByteString` to an appropriate Haskell data type without first loading the whole value into memory as an avro `Value` intermediate type).

I am not really proposing doing it right now though, just a thought that @Kheldar and myself had the other day...

**Comment by dwincort** [comment]
Yes, deconflicting the schemas directly would be great!  As you say, you're "not really proposing doing it right now", but it does sound like a fun challenge, and if I have some time in the next few weeks and you don't get to it first, I'll take a look and see if I can come up with anything good.

**Comment by AlexeyRaga** [comment]
@dwincort That would be awesome and thank you very much for your contribution!

**Comment by AlexeyRaga** [comment]
Now that I am thinking about deconflicting...

What If instead of altering schemas by expanding named types we build `Map TypeName Type`?
We don't touch the schema, and every time we see `TypeName` we look up that `Map`, get the real type and proceed with the value.

`expandNamedTypes` already builds such a map, just choses not to return it. And by not altering the schema it may even go a bit faster.

So it looks like passing a tuple like `(Schema, Map TypeName Type)` around instead of just `Schema` would do the trick for both recursive and non-recursive schemas. And it would also allow us to have that perf optimisation for the containers because we still can only build that `Map` once per container.

Of course, thinking about it in the middle of the night may drive me to wrong conclusions, but I'll try playing with this idea once I have time.

**Comment by dwincort** [comment]
For the record, I've had a little time and have been working on this.  I wrote a new version of `deconflict` with type `Schema -> Schema -> Maybe Schema` and it only required a few small changes to the `Schema` and `Field` data types.  I'm not sure it's correct yet, but it seems promising right now.  Furthermore, it feels like I could pretty easily extend this with some kind of  "final"-style system that would allow one to easily define their own parsing function, essentially providing the direct decoding you brought up in a previous comment.

I think I'll put these changes in a new branch.  If they look good, we can drop this PR in favor of that one, and if not, this is still a fallback.

**Comment by dwincort** [comment]
@AlexeyRaga See  https://github.com/haskell-works/avro/pull/123 for a new  version of schema deconflicting.

**Comment by AlexeyRaga** [comment]
@dwincort These changes should be incorporated into https://github.com/haskell-works/avro/pull/141.

Please have a look there or in [decode-optimisation](https://github.com/haskell-works/avro/tree/decode-optimisation) branch directly.

It should have reach the goals that we wanted to achieve and offers a massive (up to 3x) performance improvement thanks to @TikhonJelvis idea of encoding to Avro directly.

**Comment by dwincort** [comment]
Yes, let's close this in favor of https://github.com/haskell-works/avro/pull/141

**Pull request closed without merging**
