### PR TITLE
Switch to use zlib exclusively

### PR DESCRIPTION
**Pull request by newhoggy**

### CODE REVIEW

**Comment by imalsogreg** [comment]
I'm trying to get ghcjs to build `avro`; this doesn't work with `zlib`. Would you accept a PR that uses cabal flags to conditionally (a) replace `zlib` with `zlib-pure`, or (b) disable compression and drop the zlib dep?

**Comment by AlexeyRaga** [comment]
@imalsogreg I think that dropping compression would be impractical...
I am fine with the plan `a` unless it requires introducing many ifdefs in code and makes code less maintainable.

**Comment by newhoggy** [comment]
This is why we need backpack

**Comment by AlexeyRaga** [comment]
@newhoggy do you remember what was the reason for switching from `zlib-pure`?

Backpack is good, but you wouldn't want to backpack every utility library that you use...
AFAIK `ghcgs` should have the ability to "patch" libraries, similarly to how `eta` does it (or maybe `eta` borrowed it from `ghcjs`?), so it may also be a solution.

Also, does `backpack` have any "default" configuration? Almost all of the library users use it with `ghc`, so forcing them to `backpack` means complicating dependencies for all these users...

**Comment by newhoggy** [comment]
It wasn't so much switching from `zlib-pure`.  Rather it was using both and I changed it to use only one of the two.  You could certainly switch it to only using `zlib-pure`, but it's worth evaluating the performance implications of such a switch in case it might have some downstream impact.

**Comment by TomMD** [comment]
zlib-pure has on the readme:

> roughly 100x worse performance [vs zlib]

So make such a change with care.  It might be better to depend on a third library that normalizes the API between zlib and zlib pure then provides either one via backpack.

**Comment by newhoggy** [comment]
Worth keeping in mind that stack doesn't yet support backpack.

Personally, I'm almost ready to ditch support for stack altogether.

**Comment by AlexeyRaga** [comment]
If interface is the same, then we can simply be like:

```
  if impl(ghcjs)
    build-depends: zlib-pure
  if !impl(ghcjs)
    build-depends: zlib
```

**Comment by newhoggy** [comment]
Works for me

**Pull request merged**
