### PR TITLE
Use auto-generated avro.cabal

### PR DESCRIPTION
**Pull request by imalsogreg**
Following up with another correction to my previous oops (adding `tf-random` as a cabal dep without updating `package.yaml`)

This fix uses an `avro.cabal` file directly generated by hpack. @TikhonJelvis 's fix of my omission included a cabal file change without bumping hpack's hash in the cabal file, and this seems to be disturbing nix's build. This surprised me, I would have thought that nix simply overwrites an old cabal file with an old hash, but I suppose that would be unsafe. Anyway

Sorry for the noise!

Testing done:
 - [x] `cabal sdist`, extract tarball elsewhere, in sdist copy run `nix-shell & cabal test`

### CODE REVIEW

**Comment by TikhonJelvis** [comment]
Since the cabal file is auto-generated, can we get rid of it altogether? Would that make it hard for people to build using `cabal`?

I do not like including autogenerated files in git unless I have a really good reason for it. It's just too easy to end up in an inconsistent state by mistake.

**Comment by imalsogreg** [comment]
@TikhonJelvis Done.

Cabal users would have to run `hpack` - that's a little more difficult for anyone who is not into hpack and is building this library directly. But I think that only impacts this library's contributors. Users who import it would get the avro cabal file from the Hackage upload. So, negative impact is pretty small. And I too find hpack issues more confusing when the cabal file is checked into git. Any thougts @AlexeyRaga?

**Comment by AlexeyRaga** [comment]
I think maybe to get rid of `stack` entirely and just use `cabal new-build`.
I have created #75 to make it possible, or if there is a problem with it then I think I could just copy/paste the orb content into this project.
But the idea is to just use "normal" `.cabal` without any `hpack` etc.

What do you guys think?

**Comment by imalsogreg** [comment]
@AlexeyRaga Sounds good to me! I think in this case, the dependencies are few enough that a simple cabal file is enough.

**Comment by AlexeyRaga** [comment]
I have closed this PR because we moved away from `stack`/`hpack`/`package.yaml`

**Pull request closed without merging**
