### PR TITLE
Schema deconflict

### PR DESCRIPTION
**Pull request by AlexeyRaga**
This PR is a continuation of https://github.com/haskell-works/avro/pull/123

The original PR has been moved to its own `schema-deconflict` branch so that it can receive its own PRs.

### CODE REVIEW

**Comment by AlexeyRaga** [comment]
@dwincort I just realised that we already have this (but not all the cases):

https://github.com/haskell-works/avro/blob/master/src/Data/Avro/FromAvro.hs#L74

Do you think that we can continue using this approach? This way we'll be able to "lower" the schema while deconflicting, i.e. do `Long --> Int` instead of `Long --> IntLongCoercion` constructors?
Widening then would happen inside `FromAvro` instances.

Of course it doesn't handle ignoring/defaulting fields, but can it handle the case that we are currently solving with extra constructors?

**Comment by dwincort** [comment]
I think what you're suggesting is even more lenient than what we have.  I don't think it would affect any of my own use cases for `avro`, but it's not entirely clear to me that it's a good thing.

My example will be a little clearer if I use `IntDoubleCoercion` as opposed to `IntLongCoercion`, but it should hold for any of the coercions.

Currently, after the `getAvro` phase, we have a `T.Double` value.  This means we _know_ that the Haskell type better be `Double`, and if it isn't, we throw a `badValue` error.  This actually forces the _user_ to be honest—if the schema you're using says the value is a `Double`, you better expect a `Double`.  The `fromAvro` change you're describing actually makes things more lenient.  Internally, we're throwing away the knowledge of what the (writer) schema declares the value to be and letting the user decide.  So, if the reader schema says it's an `Int`, then even if the writer schema says it's a `Double`, there's nothing stopping the user from getting an `Int`, `Long`, `Float`, or `Double` back.

So, is making `fromAvro` generally more permissive a good idea?

In addition to the coercions, I think you could pull the same trick for `FreeUnion`.  You could add a line like the following to every `FromAvro` instance:
```haskell
  fromAvro (T.Union ts _ v) | V.length ts == 1, Success a <- fromAvro v = pure a
```
You could make things _really_ permissive by getting rid of the `V.length ts == 1` check too.

**Comment by dwincort** [comment]
@AlexeyRaga Any thoughts?

**Comment by AlexeyRaga** [comment]
@dwincort Sorry for being VERY slow on maintaining my repos.
I am VERY busy this time: looking for a new job, my son is in hospital, handing over stuff on my current/old job, etc.

I will have time to work on it more actively, hopefully soon.

But even now, I am working on this stuff, however slowly. 
And I have results!
Building on top of your branch and incorporating some of the ideas from few discussions around Avro I managed to get these performance improvements:

- Reading Avro from ByteString is ~20%+ faster on individual values. I expect it to be even faster on containers since we only need to do deconflicting once thanks to your changes. But I haven't implemented a containers benchmark yet.
- Writing Haskell types to ByteString is _at least twice_ faster. Again, only individual values so far, but I don't expect containers to be any different.

I hope to find more time to work on it so we could have something usable.

Now back to the discussion:

> Currently, after the getAvro phase, we have a T.Double value. This means we know that the Haskell type better be Double, and if it isn't, we throw a badValue error. 

I see it the other way around. 
Typically, in 99% of cases I would expect Haskell data types to be generated from Schema by TH.
Therefore user _declares_ what they want to _have at the end_.
Now, we do our schema de-conflicting and we automatically "promotes" values from one type to another to satisfy users' needs if possible. 
I think that's the essence of this process: I want my `Double`, if you only have `Float` then just convert it seamlessly so that I have my `Double` because the Spec allows me to have it. Even if it feels like a "lie" somehow :)

Let's see how it goes.

And I should write some prop tests for unions if I haven't yet. Unions are always puzzling me :)

**Pull request closed without merging**
